### ISSUE TITLE
Propuesta Consejo del Rey y Títulos Menores

### ISSUE THREAD

**Issue by C172agot** [Sauronato/AGOTSpanish#32]
Consejo del Rey
Septon Alto a Septon Supremo
Maestro de Barcos a Almirante de la Flota
Maestro de los susurrantes a Consejero de los Rumores 
Maestro de la moneda a Consejero de la Moneda
Maestro de leyes a Consejero de los Edictos

Titulos Menores
Guardián de las celdas a Carcelero
Guardián del Este a Guardián del Oriente
Guardián del oeste a Guardián del Occidente
Maestro del caballo a Caballerizo Mayor
Tonto a Bufón
Septos Septones
Maestro de la perrera a Encargado de las perreras

**Comment by Js-glez** [comment]
Arreglado para la siguiente versión.

Muchas gracias por tus comentarios.
